Repository COSC-481W-Dodo/dodo-web, pull requests merged in 2022-12, with the labels that each got.

#36 fix: Incorrect invalid form error
  src/Presentation/Views/CreateFlashcards/CreateFlashcards.tsx
  src/Presentation/Views/CreateFlashcards/CreateFlashcardsViewModel.ts
Labels: web, sprint3

#37 style: Update style of NavBar
  src/App.css
  src/Presentation/Components/NavigationBar.tsx
  src/Presentation/Components/navigation-bar.css
  src/dodo.png
Labels: web, sprint3, UI/UX

#38 style: Update favicon
  public/android-chrome-192x192.png
  public/android-chrome-384x384.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: maintenance, web, sprint3

#40 chore: Update android link for sprint 3
  src/Presentation/Views/Home/Home.tsx
Labels: web, sprint3

#42 fix: Update Android link with bug fix
  src/Presentation/Views/Home/Home.tsx
Labels: web, sprint3
